language: python

# use container-based travis-ci infrastructure
#sudo: false

# use legacy infrastructure
sudo: required

matrix:
  include:
    - python: "2.7"
      env: PYTHON_BINARY="python2.7"
      before_install:
        - pip install virtualenv

    - python: "3.4"
      env: PYTHON_BINARY="python3.4"
      addons:
        apt:
          packages:
          - python3-setuptools
          - python3-dev

    - python: "3.5"
      env: PYTHON_BINARY="python3.5"
      addons:
        apt:
          sources:
          # apt source hosting Python3.5 and 3.6
          - deadsnakes
          packages:
          # Travis-ci has a known issue with Python3.5 and 3.6
          - python3.5
          - python3-setuptools
          - python3-dev

    - python: "3.6"
      env: PYTHON_BINARY="python3.6"
      addons:
        apt:
          sources:
          # apt source hosting Python3.5 and 3.6
          - deadsnakes
          packages:
          # Travis-ci has a known issue with Python3.5 and 3.6
          - python3.6
          - python3-setuptools
          - python3-dev

services:
  - docker

before_install:
  # deactivate Travis-CI Python3 VirtualEnv, as it conflicts with the launch.py one
  - deactivate

install:
  # mongodb section
  - docker pull mongo:3
  - sudo mkdir --mode=777 -p /data/db/
  - docker run -d --name syn-mongo -v /data/db/:/data/db -p 27017:27017 mongo:3 --storageEngine wiredTiger

  # rabbit mq section
  - docker pull rabbitmq:3
  - docker run -d --hostname syn-rabbit --name syn-rabbit -p 5672:5672 rabbitmq:3
  - docker run -d --hostname syn-rabbit --name syn-rabbit-mgr -p 15672:15672 rabbitmq:3-management
  - wget http://127.0.0.1:15672/cli/rabbitmqadmin -O /tmp/rabbitmqadmin
  - python3 /tmp/rabbitmqadmin declare exchange name=ex_utils type=direct
  - python3 /tmp/rabbitmqadmin declare exchange name=ex_managed_worker type=direct
  - python3 /tmp/rabbitmqadmin declare exchange name=ex_freerun_worker type=direct
  - python3 /tmp/rabbitmqadmin declare vhost name=unit_test
  - python3 /tmp/rabbitmqadmin declare exchange --vhost=unit_test name=ex_utils type=direct
  - python3 /tmp/rabbitmqadmin declare exchange --vhost=unit_test name=ex_managed_worker type=direct
  - python3 /tmp/rabbitmqadmin declare exchange --vhost=unit_test name=ex_freerun_worker type=direct

before_script:
  - echo "PATH=${PATH}"
  - sudo mkdir --mode=777 -p /var/log/synergy-scheduler
  - ${PYTHON_BINARY} launch.py install
  - python3 launch.py db --reset

script:
  - ${PYTHON_BINARY} launch.py test

branches:
  only:
    - master
    - 2.0
    - 2.1
