language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
services:
  - rabbitmq
  - mongodb
# use container-based travis-ci infrastructure
sudo: false

install:
  - mkdir -p /mnt/logs/synergy-scheduler
  - pip install virtualenv
  - python ./launch.py install
  - python ./launch.py db --reset

script:
  - python ./launch.py test

branches:
  only:
    - master
    - 1.15