#  Bitbucket Pipeline definition for Scheduler
image: python:3.7.3

definitions:
  services:
    mongodb:
      image: mongo:3

    rabbitmq:
      image: rabbitmq:3
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

pipelines:
  default:
      - step:
          name: Setup Env and Run Test
          script:
#            - pip install python3-setuptools
#            - echo "127.0.0.1 syn-rabbitmq" >> /etc/hosts
#            - echo "127.0.0.1 syn-mongodb" >> /etc/hosts
            - cat /etc/hosts
            - RABBITMQ_HOST=localhost scripts/rabbitmq_config.sh
            - mkdir --mode=777 -p /var/log/synergy-scheduler
            - python launch.py install
            - python launch.py db --reset
            - python launch.py test

          services:
            - mongodb
            - rabbitmq
